import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import PageTransition from "../components/PageTransition";
import BackgroundEffects from "../components/BackgroundEffects";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.variable} antialiased bg-black`}>
        <BackgroundEffects />
        <div className="relative z-10">
          <Navbar />
          <PageTransition>{children}</PageTransition>
        </div>
      </body>
    </html>
  );
}
